# -*- coding: utf-8 -*-
from . import account_account
from . import oi_fin_data
from . import oi_fin_datatmpl
from . import oi_fin_report_source
from . import oi_fin_template_column
from . import oi_fin_template_row
from . import oi_fin_template
from . import oi_fin_template_column_t
from . import oi_fin_template_row_t
from . import oi_fin_report
from . import oi_fin_report_currency_rate
from . import oi_fin_aged_partner_template
from . import oi_fin_aged_partner_template_line
from . import oi_fin_aged_partner_wizard
from . import oi_fin_aged_partner_wizard_line
from . import oi_fin_dimension
from . import account_move
from . import account_move_line